# Generated by Django 2.2.4 on 2020-08-19 15:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('pdf', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Pdf',
            new_name='Customer',
        ),
    ]
